pyproject.toml: fix installation using pip by adding authors
Pip installation, at least in non-editable mode, requires the authors
section. Otherwise there is an error:

  RuntimeError: The Poetry configuration is invalid:
  - The fields ['authors'] are required in package mode.